### ISSUE TITLE
Unable to load the project fully(missing scripts)

### ISSUE THREAD

**Issue by tarnos12** [ericoporto/galleys#1]
Hey,

Perhaps it is missing some files on GitHub, but opening the project in AGS 3.6 does not load all scripts.
Scripts are in the game folder, but they don't appear in the editor.
TileMap script is one example, but there are more.

Any ideas what might be the issue?

Thanks

**Comment by ericoporto** [comment]
So, it turns out I forgot to push a commit @tarnos12 , sorry for taking so long. I plan to make a writeup on it later.

Edit: Looking at the diff, I remember now, I did not want to push the SpeechCenter plugin change along, but I just tested in an editor without SpeechCenter and it simply loads a window telling it will remove speech center related things on save... I use way too many AGS Editors. :/

**Comment by tarnos12** [comment]
Thanks!

We also use some extra editors and it works just fine even if others don't use it.

**Comment by ericoporto** [comment]
Cool. I do plan to add a text description on how it works in the readme, so I am keeping this open so I can poke once I am done.

The graphic assets here are a modified version of assets that were made for a web dungeon crawler that was open sourced and is not made by me. I picked it up the renderer parts of this dungeon crawler and adapted here to explore the possibilities within AGS.
